Add test for version override

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -136,6 +136,18 @@ jobs:
             exit 1
           fi
 
+      - name: Check version override
+        shell: bash
+        run: |
+          gh codeql set-version latest
+          gh codeql download v2.7.6
+          VERSION=`GH_CODEQL_VERSION=v2.7.6 gh codeql version --format json | jq -r '.version'`
+
+          if [[ $VERSION != "2.7.6" ]]; then
+            echo "::error::Expected version 2.7.6 but got $VERSION"
+            exit 1
+          fi
+
       - name: Check use of stub
         shell: bash
         run: |
