Add test for `install-stub` command

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -135,3 +135,18 @@ jobs:
             echo "::error::Expected version 2.6.0+202108311306 but got $VERSION"
             exit 1
           fi
+
+      - name: Check use of stub
+        shell: bash
+        run: |
+          VERSION=`gh codeql version --format json | jq -r '.version'`
+
+          mkdir temp
+          gh codeql install-stub temp
+          OTHER_VERSION=`temp/codeql version --format json | jq -r '.version'`
+          if [[ $OTHER_VERSION != $VERSION ]]; then
+            echo "::error::Expected version $VERSION but got $OTHER_VERSION"
+            exit 1
+          fi
+
+          rm -r temp
